### ISSUE TITLE
Why do we have separate training files?

### ISSUE THREAD

**Issue by kbatsuren** [sigmorphon/2022InflectionST#1]
Hi @jkodner05,

Could you describe the reason for having separate training files? Or do we have to train 10 different models for each of them?
Can we train the model by merging all separate training files into one train file?

Best regards,
Huygaa

**Comment by jkodner05** [comment]
The intent is for you to train a model for each training file. The smaller training files are subsets of the larger ones

**Comment by kbatsuren** [comment]
Thanks for the answer!
